# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Standalone Demo - ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Standalone Demo - ObjC
pod 'HyBid', '2.12.1'
end
