# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Standalone Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Standalone Demo
pod 'HyBid', '2.19.0'
pod 'OneTrust-CMP-XCFramework','~>202308.2.0.0'
end
